version: "3.9"

services:
  postgres:
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat_db
      APP_DB_USER: docker
      APP_DB_PASS: docker
    networks:
      - main-net
    volumes:
      - ./scripts/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

volumes:
  pgdata:
    driver: local

networks:
  main-net:
    driver: bridge
