POST http://localhost:8080/register
Content-Type: application/json
Accept: application/json

{
  "login": "kok",
  "password": "zzz"
}

###

POST http://localhost:8080/login
Content-Type: application/json
Accept: application/json

{
  "login": "kok",
  "password": "zza"
}

###

POST http://localhost:8080/connect
Content-Type: application/json
Accept: application/json

###

POST http://localhost:8080/send/da322e25-1c9d-493c-81f6-7951521f515f
Content-Type: application/json
Accept: application/json

{
  "userId": "72ca52dc-7ec5-4e67-ae1b-a266b1548031",
  "message": "hello you!"
}

###

GET http://localhost:8080/chat/54d781a8-6fe5-4f5e-a142-b65894d288ef?userId=6e551275-0977-4208-a63c-b925cc45b82b
Accept: application/json

###

POST http://localhost:8080/close/da322e25-1c9d-493c-81f6-7951521f515f
Content-Type: application/json
Accept: application/json

{
  "userId": "72ca52dc-7ec5-4e67-ae1b-a266b1548031"
}

###

GET http://localhost:8080/hello/myname
Accept: text/plain

###
